[package]
name = "pulao-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.26.1"
ssh2 = "*"
subprocess = "0.2.9"
clap = { version = "3.0.0-rc.8", features = ["derive"] }
